<div class="tab-pane fade in active" id="tab1">
	<div id="t_general" class="tab">
		<div class="form-group">
			<div class="col-sm-12">
				<legend><?=_('Create new mail')?></legend>                    
			</div>
		</div>
        
        <div class="form-group">
            <div class="col-sm-8" class="form-control">
                <label><?=_('Subject')?></label>
                <input type="text" class="form-control" name="oggetto" value="<?=$data->item->oggetto?>"/>
            </div>
            <div class="col-sm-4 " class="form-control">
                <label><?=_('Email of test')?></label>
                <input type="text" class="form-control" name="testing" value="<?=$data->item->testing?>" />
            </div>
        </div>
        <!--div class="form-group">
            <div class="col-sm-4 col-sm-offset-8" class="form-control">
                <label>Programma</label>
                <input type="text" class="form-control" value="" readonly="readonly"/>
            </div>
        </div-->        
        <div class="form-group">
            <div class="col-sm-12" class="form-control">
                <label><?=_('Message (HTML)')?></label>
                <textarea class="form-control" name="messaggio_html" id="messaggio_html"><?=$data->item->messaggio_html?></textarea>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-12" class="form-control">
                <label><?=_('Message (TEXT)')?></label>
                <textarea class="form-control" name="messaggio_text" rows="6"><?=$data->item->messaggio_text?></textarea>
            </div>
        </div>
        
	</div>
</div>


<script>    
    CKEDITOR.replace( 'messaggio_html' );
</script>
