<div class="tab-pane fade in active" id="tab1">
	<div id="t_general" class="tab">
		<div class="form-group">
			<div class="col-sm-12">
				<legend>Crea una Email</legend>                    
			</div>
		</div>
        
        <div class="form-group">
            <div class="col-sm-8" class="form-control">
                <label>Oggetto</label>
                <input type="text" class="form-control" name="oggetto" value="<?=$data->item->oggetto?>"/>
            </div>
            <div class="col-sm-4 " class="form-control">
                <label>Indirizzo Email di Test</label>
                <input type="text" class="form-control" name="testing" value="<?=$data->item->testing?>" />
            </div>
        </div>
        <div class="form-group">
            <!--<div class="col-sm-4 col-sm-offset-8" class="form-control">
                <label>Programma</label>
                <input type="text" class="form-control" value="" readonly="readonly"/>
            </div>-->
        </div>
        
        <div class="form-group">
            <div class="col-sm-12" class="form-control">
                <label>Messaggio (HTML)</label>
                <textarea class="form-control" name="messaggio_html" id="messaggio_html"><?=$data->item->messaggio_html?></textarea>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-12" class="form-control">
                <label>Messaggio (TEXT)</label>
                <textarea class="form-control" name="messaggio_text" rows="6"><?=$data->item->messaggio_text?></textarea>
            </div>
        </div>
        
	</div>
</div>


<script>    
    CKEDITOR.replace( 'messaggio_html' );
</script>
