<div class="row">

	<?php foreach($app->getMenu('dashboard') as $i => $panel) { ?>
	
		<div class="col-md-4" id="<?=$panel['id']?>" >

			<div class="panel panel-default">
				<div class="panel-heading">
					<?=$panel['label']?>
				</div>
				<div class="panel-body">
					<ul>
						<?php foreach($panel['children'] as $item) { ?>
							<li>
								<a href="<?=$item['link']?>"><?=$item['label']?></a>
							</li>	
						<?php } ?>
					</ul>
				</div>
			</div>

		</div>
  
	<?php if ($i>0 && $i % 2 == 0) echo "</div> <div class='row'>";
    } ?>
</div>

<div class="row">
    <?php foreach($app->getMenu('dashboard-button') as $i => $button) { ?>
            <div class="col-md-3 col-sm-3">
                <a href="<?=$button['link']?>" type="button" class="btn-block btn btn-<?=$button['type']?> btn-lg"><span class="<?=$button['icon']?>" aria-hidden="true"></span> &nbsp; <?=$button['label']?></a>
            </div>
    <?php if ($i>0 && $i % 3 == 0) echo "</div> <div class='row'>";
    } ?>    
</div>

<div class="row">
    
    <div class="col-md-6" id="" >
        <div class="panel panel-default">
            <div class="panel-heading">
                System info
            </div>
            <div class="panel-body">
                Informazioni rapide sullo stato del sistema.<br />
                * Numero di email inviabili giornalmente<br />
                * Numero di email inviate dall'inizio <br />
                * Numero di email rimanenti da inviare oggi.<br />
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                  <span class="badge"><?=$data->max_mail;?></span>
                  Send Mail for Day
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->remain?></span>
                  Remain Mail for Day
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->tosend?></span>
                  In coda d'invio                  
                </li>
            </ul>
        </div>

    </div>
    
    <div class="col-md-6" id="" >
        <div class="panel panel-default">
            <div class="panel-heading">
                Contact Info
            </div>
            <div class="panel-body">
                Informazioni rapide sui contatti inserite all'interno del sistema <b>MailCtlr</b>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                  <span class="badge"><?=$data->contatti?></span>
                  Total Contact
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->liste?></span>
                  Total List
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->total?></span>
                  Total Send Mail
                </li>                
            </ul>
        </div>

    </div>
    
</div>
<br />