<!--<div class="row">

	<?php foreach($app->getMenu('dashboard') as $i => $panel) { ?>
	
		<div class="col-md-4" id="<?=$panel['id']?>" >

			<div class="panel panel-default">
				<div class="panel-heading">
					<?=$panel['label']?>
				</div>
				<div class="panel-body">
					<ul>
						<?php foreach($panel['children'] as $item) { ?>
							<li>
								<a href="<?=$item['link']?>"><?=$item['label']?></a>
							</li>	
						<?php } ?>
					</ul>
				</div>
			</div>

		</div>
  
	<?php if ($i>0 && $i % 2 == 0) echo "</div> <div class='row'>";
    } ?>
</div>-->
<div class="row">
    <?php foreach($app->getMenu('dashboard-button') as $i => $button) { ?>
            <div class="col-md-3 col-sm-3">
                <a href="<?=$button['link']?>" type="button" class="btn-block btn btn-<?=$button['type']?> btn-lg"><span class="<?=$button['icon']?>" aria-hidden="true"></span> &nbsp; <?=$button['label']?></a>
            </div>
    <?php if ($i>0 && $i % 3 == 0) echo "</div> <div class='row'>";
    } ?>    
</div>
<div class="row">
    <div class="col-md-6" id="" >
        <div class="panel panel-default">
            <div class="panel-heading">
                <?=_('System info')?>
            </div>
            <div class="panel-body">
                <?=_('Quick information about system status.')?><br />
                <?=_('* Number of e-mail can be sent daily')?><br />
                <?=_('* Number of emails sent from the start')?><br />
                <?=_('* Remaining number of emails to be sent today.')?><br />
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                  <span class="badge"><?=$data->max_mail;?></span>
                  <?=_('Send Mail for Day')?>
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->remain?></span>
                  <?=_('Remain Mail for Day')?>
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->tosend?></span>
                  <?=_('In the send queue')?>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-6" id="" >
        <div class="panel panel-default">
            <div class="panel-heading">
                <?=_('Contact Info')?>
            </div>
            <div class="panel-body">
                <?=sprintf(_('Quick information about contacts entered into the system <b>%s</b>',$app->name))?>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                  <span class="badge"><?=$data->contatti?></span>
                  <?=_('Total Contact')?>
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->liste?></span>
                  <?=_('Total List')?>
                </li>
                <li class="list-group-item">
                  <span class="badge"><?=$data->total?></span>
                  <?=_('Total Send Mail')?>
                </li>                
            </ul>
        </div>
    </div>
</div>
<br />