<form action="<?=__HOME__?>/user/save/" method="POST" data-ui-validate="success:'<?=$data->modal?'testModalSave':''?>'" id="item">
	<input type="hidden" name="id" value="<?=$data->item->id?>" />
    <div >
        <label><?=_('Username')?>*</label>
        <input data-ui-testing="required min3" type="text" name="username" value="<?=$data->item->username?>">
        <div data-ui-message="error:username:required">
           <?=_('Username is required!')?>
        </div>
        <div data-ui-message="error:username:min3">
           <?=_('Min lengh is 3')?>
        </div>
    </div>
    <div>
        <label><?=_('Password')?>*</label>
        <input data-ui-testing="required min3" type="text" name="password" value="<?=$data->item->password?>">
        <div data-ui-message="error:password:required">
            <?=_('Password is required!')?>
        </div>
        <div data-ui-message="error:password:min3">
           <?=_('Min lengh is 3')?>
        </div>
    </div>
    <div>
        <label><?=_('Name')?></label>
        <input type="text" name="nome" value="<?=$data->item->nome?>">
    </div>
    <div>
        <label><?=_('Surname')?></label>
        <input type="text" name="cognome" value="<?=$data->item->cognome?>">
    </div>
    <div>
        <label><?=_('Email')?></label>
        <input type="text" name="email" value="<?=$data->item->email?>">
    </div>
    <div>
        <label><?=_('Phone')?></label>
        <input type="text" name="telefono" value="<?=$data->item->telefono?>">
    </div>
    <div>
        <label><?=_('Mobile phone')?></label>
        <input type="text" name="cellulare1" value="<?=$data->item->cellulare1?>">
    </div>
    <div>
        <label><?=_('Mobile phone 2')?></label>
        <input type="text" name="cellulare2" value="<?=$data->item->cellulare2?>">
    </div>
    <select name="role">
        <option value="user" <?=$data->item->role=='user'?'selected':''?>>user</option>		
        <option value="admin" <?=$data->item->role=='admin'?'selected':''?>>admin</option>		
        <option value="superadmin" <?=$data->item->role=='superadmin'?'selected':''?>>superadmin</option>
    </select>
    <span>* <?=_('Required')?></span>
</form>