language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update

script: phpunit


matrix:
  allow_failures:
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always