<div class="modal fade " id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm"> 
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="myModalLabel">
					Attenzione...
				</h4>
			</div>
			<div class="modal-body">
				Vuoi davvero eliminare questo record?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a id="confirm-delete" href="javascript:;" class="btn btn-danger">
					<i class="glyphicon glyphicon-trash"></i> 
					Elimina
				</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#modal-delete').on('show.bs.modal', function (e) {		
		$("#confirm-delete").attr("href",$(e.relatedTarget).attr("data-delete-url"));
	});
</script>	