<!DOCTYPE html>
<html lang="<?=__LANG__?>">
<head>
<title><?=$app->name?></title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" href="https://bootswatch.com/simplex/bootstrap.min.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/jquery.autocomplete.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/uploadify.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/jquery-ui-1.8.4.custom.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/jquery-ui.dataTables.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/jquery.dataTables.css">
<link rel="stylesheet" href="<?=__URL__?>/theme/default/css/jquery.ui.override.css">		
<link rel="stylesheet" href="<?=__URL__?>/theme/default/css/style.css">
<script>var PUBLIC_URL="<?=__URL__?>/public";</script>
<script src="<?=__URL__?>/public/js/jquery.min.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/hook.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/jquery-ui.min.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/jquery.uploadify.min.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/jquery.dataTables.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/bootstrap.min.js?ts=<?=time()?>"></script>
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/i18n/jquery-ui-i18n.min.js?ver=4.1'></script>
<script src="<?=__URL__?>/public/js/common-ui.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/common-ui-uploadify.js?ts=<?=time()?>"></script>
<script src="<?=__URL__?>/public/js/common-ws.js?ts=<?=time()?>"></script>
<script>$ui.setLocale('en');</script>
<script>$ws.base = "<?=__HOME__?>";</script>
<script src="<?=__URL__?>/public/js/common.js"></script>
<?=$app->render_hook('append-js')?>
</head> 
<body>