<!DOCTYPE html>
<html lang="<?=__LANG__?>">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<!--<link rel="shortcut icon" href="<?=__URL__?>/public/images/favicon.ico">-->
<title><?=__NAME__?></title>
<link href="<?=__URL__?>/public/css/bootstrap.min.css" rel="stylesheet">
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<div class="container">
	<div style="text-align:center">
		 <a href="<?=__HOME__?>/login">
			<img src="<?=__LOGO__?>" alt="<?=__NAME__?>">				
		</a>
	</div>
	<form action="<?=__HOME__?>/Login/Login" class="form-signin" role="form" method="POST">
		<?php if (isset($_GET["alert"])) { ?>
			<div class="alert alert-danger">
				<?=$_GET["alert"]?>
			</div>
		<?php } ?>
		<br/>        
		<input type="text" name="username" class="form-control" placeholder="<?=_('Username')?>" required autofocus>		
		<input type="password" name="password" class="form-control" placeholder="<?=_('Password')?>" required>
		<input type="hidden" name="redirect" value="<?=@$_GET["redirect"];?>">
		<!--label class="checkbox">
			<input type="checkbox" value="remember-me"> Remember me
		</label-->
		<button class="btn btn-lg btn-primary btn-block" type="submit"><?=_('Sign In')?></button>
	</form>
</div>
<style>
	body {
		padding-top: 40px;
		padding-bottom: 40px;
		background-color: #eee;
	}
	.form-signin {
		max-width: 330px;
		padding: 15px;
		margin: 0 auto;
	}
	.form-signin .form-signin-heading,
	.form-signin .checkbox {
		margin-bottom: 10px;
	}
	.form-signin .checkbox {
		 font-weight: normal;
	}
	.form-signin .form-control {
	  position: relative;
	  height: auto;
	  -webkit-box-sizing: border-box;
		 -moz-box-sizing: border-box;
			  box-sizing: border-box;
	  padding: 10px;
	  font-size: 16px;
	}
	.form-signin .form-control:focus {
	  z-index: 2;
	}
	.form-signin input[name="username"] {
	  margin-bottom: -1px;
	  border-bottom-right-radius: 0;
	  border-bottom-left-radius: 0;
	}
	.form-signin input[type="password"] {
	  margin-bottom: 10px;
	  border-top-left-radius: 0;
	  border-top-right-radius: 0;
	}
</style>
</body>
</html>