<div class="h70px">
	<nav 	
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation" 
		>
		<div class="container">
			<div class="navbar-header">    
				<span class="navbar-brand nav-bar-title" ><?=@$data->title ?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
			<div class="navbar-content collapse navbar-collapse">		
				<ul class="nav navbar-nav pull-right">
					<li>
						<button 
							type="button" 
							data-placement="bottom" 
							data-toggle="tooltip" 
							class="navbar-btn btn btn-default" 
							onClick="location.href='<?php echo $data->createUrl ?>'" >
							<span class="glyphicon glyphicon-plus"></span> <?=_('New')?>
                        </button>&nbsp;
					</li>
                    <li>
						<button 
							type="button"
                            data-toggle="modal" 
                            data-target="<?php echo $data->modal ?>"
							data-placement="bottom" 
							class="navbar-btn btn btn-default"  >
							<span class="glyphicon glyphicon-list"></span> <?=_('Process queue')?>
						</button>&nbsp;
					</li>
                    <li>
						<button 
							type="button" 
							data-placement="bottom" 
							data-toggle="tooltip" 
							class="navbar-btn btn btn-default" 
							onClick="location.href='<?php echo $data->realTime ?>'" >
							<span class="glyphicon glyphicon-asterisk"></span> <?=_('Real Time')?>
                        </button>&nbsp;
					</li>
				</ul>
			</div>
		</div>
	</nav>
</div>	