<div class="h70px">

	<nav 	
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation" 
		>

		<div class="container">

			<div class="navbar-header">    
				<span class="navbar-brand nav-bar-title" ><?=@$data->title ?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
			<div class="navbar-content collapse navbar-collapse">		
                            <div class="nav navbar-nav pull-right">
                                <button 
                                    id="tasto-cancella-ricerca"
                                    type="button" 
                                    class="btn btn-warning"
                                    style="display:none;"
                                    onclick="fix_datagrid_cancella_ricerca()"
                                    >
                                    Cancella ricerca
                                </button>
                                <button 
                                    type="button" 
                                    data-toggle="tooltip" 
                                    data-original-title="Torna alla scermata precedente" 
                                    class="navbar-btn btn btn-success" 
                                    onclick="javascript:history.go(-1);" 
                                    >
                                    <span class="glyphicon glyphicon-chevron-left <!--glyphicon glyphicon-remove-->"></span> Ritorna Indietro
                                </button>                                
                            </div>
                            <!--<div id="tasto-cancella-ricerca" class="nav navbar-nav pull-right">
                                <button 
                                    type="button" 
                                    class="btn btn-warning"
                                    onclick="fix_datagrid_cancella_ricerca()"
                                    >
                                    Cancella ricerca
                                </button>
                            </div>-->
			</div>
		</div>

	</nav> 

</div>	