<div class="h70px">
	<nav 
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation"
		>
		<div class="container">
			<div class="navbar-header" >    
				<span class="navbar-brand nav-bar-title " ><?=@$data->title?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
			<div class="navbar-content collapse navbar-collapse">		
				<div class="pull-right">
					<button 
						type="button" 
						data-toggle="tooltip" 
						data-original-title="<?=_('Go back')?>" 
						class="navbar-btn btn btn-default" 
						onclick="javascript:history.go(-1);" 
						>
						<span class="glyphicon glyphicon-chevron-left"></span> <?=_('Go Back')?>
					</button>
					<button 
						class="navbar-btn btn btn-default btn-primary" 
						type="button" 
						onclick="javascript:submitForm();" 
						data-toggle="tooltip" 
						data-original-title="<?=_('Save currtent item')?>"
						>
						<span class="glyphicon glyphicon-chevron-down"></span> <?=_('Save')?>
					</button>
				</div>
			</div>
		</div>
	</nav>
</div>	