<div class="h70px">
	<nav 	
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation" 
		>
		<div class="container">

			<div class="navbar-header">    
				<span class="navbar-brand nav-bar-title" ><?=@$data->title ?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
			<div class="navbar-content collapse navbar-collapse">		
                            <div class="nav navbar-nav pull-right">
                                <button 
                                    type="button" 
                                    data-toggle="tooltip" 
                                    data-original-title="Torna alla scermata precedente" 
                                    class="navbar-btn btn btn-success" 
                                    onclick="javascript:history.go(-1);" 
                                    >
                                    <span class="glyphicon glyphicon-chevron-left <!--glyphicon glyphicon-remove-->"></span> Ritorna Indietro
                                </button>
                                <a
                                    class="navbar-btn btn btn-default" 					
                                    href="<?=$data->viewUrlSmall?>"
                                    >
                                    <span class="glyphicon glyphicon-zoom-in"></span> Espandi SMALL
                                </a>
                                <a
                                    class="navbar-btn btn btn-default" 					
                                    href="<?=$data->viewUrl?>"
                                    >
                                    <span class="glyphicon glyphicon-zoom-in"></span> Espandi FULL
                                </a>
                                <a 
                                    class="navbar-btn btn btn-default" 					
                                    href="<?=$data->pdfUrlSmall?>" 
                                    target="_blank"
                                    >
                                    <span class="glyphicon glyphicon-file"></span> PDF SMALL
                                </a>   
                                <a 
                                    class="navbar-btn btn btn-default" 					
                                    href="<?=$data->pdfUrl?>" 
                                    target="_blank"
                                    >
                                    <span class="glyphicon glyphicon-file"></span> PDF FULL
                                </a>                                
                            </div>
			</div>
		</div>

	</nav> 

</div>	