<?php include(__THEME__.'/nav-list.phtml') ?>

<div class="row">
    <div class="form-legend">
        <?=_('Uploaded Files')?>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            <div 
                data-ui-uploadify="
                    folder:'Import',
                    parent: '<?=@$data->user?>',
                    service:'<?=__HOME__?>/contact/files'
                "
                >
            </div>
        </div>
        <div style="clear:both"></div>		
    </div>
</div>