<div class="container">
    <h2><?=_('Press the START button to begin the process of cleaning the contacts!')?></h2>
    <h4><?=sprintf(_('Checks to do: <b>%s</b> -  Number of checks remaining: <b id="remain">%s</b>'),@$data->totale,@$data->number)?></h4>
    <br />
    <div class="row">
        <div class="col-sm-2">
            <label><?=_('Delete duplicate')?></label>
            <select class="form-control" id="duplicate" name="duplicati">
                <option value="1"><?=_('Yes')?></option>
                <option value="0" selected=""><?=_('No')?></option>
            </select>
        </div>
        <div class="col-sm-2">
            <label><?=_('Delete inactive')?></label>
            <select class="form-control" id="active" name="active">
                <option value="0" selected=""><?=_('No')?></option>
                <option value="1"><?=_('Yes')?></option>
            </select>
        </div>
        <div class="col-sm-2">
            <label><?=_('Process for time')?></label>
            <input type="number" class="form-control" id="limit" name="limit" value="1" />
        </div>
        <div class="col-sm-2">
            <label><?=_('Enter in')?></label>
            <select class="form-control" id="lista" name="lista">
                <option value="0" selected=""><?=_('Nowhere')?></option>
                <?php foreach($data->liste as $ls){?>
                <option value="<?=$ls->id?>"><?=$ls->nome?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-sm-2">
            <label><?=_('Request privacy')?></label>
            <select class="form-control" id="privacy" name="privacy">
                <option value="0" selected=""><?=_('No')?></option>
                <option value="1"><?=_('Yes')?></option>
            </select>
        </div>
        <div class="col-sm-2">
            <label>Email privacy</label>
            <select class="form-control" id="p_email" name="p_email">
                <option value="0" selected=""><?=_('Nowhere')?></option>
                <?php foreach($data->email as $em){?>
                <option value="<?=$em->id?>"><?=$em->oggetto?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <!-- START / STOP BUTTON -->
    <div class="row">
        <div class="col-sm-1 col-sm-offset-11">
            <label>&nbsp;</label>
            <button 
                type="button" 
                id="start"
                data-placement="bottom" 
                data-toggle="tooltip" 
                class="navbar-btn btn btn-success" 
                onClick="process( '<?=$data->action?>' , <?=$data->number?> , <?=@$data->totale?> );" >
                <span class="glyphicon glyphicon-play"></span> <?=_('Start')?>
            </button>
            <button 
                type="button" 
                id="stop"
                style="display:none;"
                data-placement="bottom" 
                data-toggle="tooltip" 
                class="navbar-btn btn btn-danger" 
                onClick="process_stop();" >
                <span class="glyphicon glyphicon-stop"></span> <?=_('Stop')?>
            </button> 
        </div>
    </div>
    <!-- PROGRESS BAR ACTIVITY -->
    <div class="row">
        <div class="col-sm-12">
            <div class="progress">
                <div 
                    id = "progress"
                    class="progress-bar progress-bar-striped active" 
                    role="progressbar" 
                    aria-valuemax="100" 
                    style="width: 0%">
                        0% <?=_('Complete')?>
                </div>
            </div>
        </div>
    </div>
    <br />
    <textarea rows="20" readonly="readonly" class="result form-control"></textarea>
</div>