<div class="tab-pane fade in active" id="tab1">
	<div id="t_general" class="tab">
		<div class="form-group">
			<div class="col-sm-12">
				<legend>Crea coda di invio</legend>                    
			</div>
		</div>
        
        <div class="form-group">
            <div class="col-sm-6" class="form-control">
                <label>Send to (LISTA)</label>
                <input type="text" class="form-control" name="lista" value=""/>
            </div>
            <div class="col-sm-6" class="form-control">
                <label>Email to send (EMAIL)</label>
                <input type="text" class="form-control" name="email" value=""/>
            </div>
        </div>
        
	</div>
</div>


