<div class="tab-pane fade in active" id="tab1">
	<div id="t_general" class="tab">
		<div class="form-group">
			<div class="col-sm-12">
				<legend>Dati generali</legend>                    
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-6" class="form-control">
				<label >Lista</label>
				<input type="text" class="form-control" name="lista_id" value="<?=$data->item->lista_id?>"/>                  
			</div>
            <div class="col-sm-6" class="form-control">
				<label >Contatto</label>
				<input type="text" class="form-control" name="contatto_id" value="<?=$data->item->contatto_id?>"/>                  
			</div>
            
        </div>
        
        <div class="form-group">
			<div class="col-sm-1" class="form-control">
				<label >Attivo</label>
                <select class="form-control" name="active">
                    <option disabled="disabled">Scegli</option>
                    <option value="0" <?=$data->item->active=='0'?'selected':'';?>>No</option>
                    <option value="1" <?=$data->item->active=='1'?'selected':'';?>>Si</option>
                </select>                   
			</div>
			<div class="col-sm-11" class="form-control">
				<label >Creata</label>
                <input readonly="readonly" type="text" class="form-control" name="creata" value="<?=$data->item->creata?>"/>                  
			</div>
        </div>
        
        
	</div>
</div>


