<?php include(__THEME__.'/nav-list.phtml') ?>


<?=

sprintf(_('Enter the form within your website to collect new subscriptions to the list <b>%s</b>'),@$data->lista->nome)?>
<br /><br />

<pre><?=htmlspecialchars('
<form action="'.__HOME__.'/remote/subscribe/" method="post">
    <input type="hidden" name="lista" value="'.@$data->lista->id.'" />
    <input type="email" name="email" value="" placeholder="'._('Enter your email').'" />
    <input type="text" name="nome" value="" placeholder="'._('Enter your name').'" />
    <input type="text" name="cognome" value="" placeholder="'._('Enter your surname').'" />
    
    <input type="radio" name="privacy" value="1"/>'.sprintf('I consent to the processing of <a href="%s">privacy</a>',@$data->lista->privacy_url).'
    <input type="submit" value="'._('Sign Up').'" />
    <input type="hidden" name="return" value="'.__HOME__.'" />
</form>');?>
</pre>

