<form 
    id="item"
	method="POST" 
	action="<?=__HOME__?>/install/install/"
	>
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend><?=_('Application information')?></legend>                    
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label><?=_('Application Name')?></label>
            <input type="text" class="form-control" name="nome_app" value="MailCtlr" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label><?=_('Language')?></label>
            <select name="lang" class="form-control">
                <?php foreach ($data->lang as $l ){ ?>
                <option value="<?=$l['lang']?>"><?=$l['lang']?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend><?=_('Database')?></legend>                    
        </div>
    </div>
    
    <div class="form-group">
         <div class="col-sm-12" class="form-control">
             <label><?=_('DB Host')?></label>
             <input type="text" class="form-control" name="host" value="" placeholder="localhost" />
         </div>
    </div>
    
    <div class="form-group">
         <div class="col-sm-6" class="form-control">
             <label><?=_('DB User')?></label>
             <input type="text" class="form-control" name="user" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
             <label><?=_('DB Password')?></label>
             <input type="text" class="form-control" name="pass" value="" />
        </div>
        
    </div>
    
    <div class="form-group">
         <div class="col-sm-6" class="form-control">
             <label><?=_('DB Name')?></label>
             <input type="text" class="form-control" name="name" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
             <label><?=_('Prefix')?></label>
             <input type="text" class="form-control" name="pref" value="" placeholder="mc_"/>
        </div>
        
    </div>
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend><?=_('Admin user data')?></legend>                    
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label><?=_('Username')?></label>
            <input type="text" class="form-control" name="u_username" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
            <label><?=_('Password')?></label>
            <input type="text" class="form-control" name="u_password" value="" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label><?=_('Name')?></label>
            <input type="text" class="form-control" name="nome" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
            <label><?=_('Surname')?></label>
            <input type="text" class="form-control" name="cognome" value="" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-7" class="form-control">
            <label><?=_('Email')?></label>
            <input type="email" class="form-control" name="email" value="" />
        </div>
        <div class="col-sm-2" class="form-control">
            <label><?=_('Newsletter')?></label>
            <select class="form-control" name="news">
                <option value="1" selected="">SI</option>
                <option value="0">NO</option>
            </select>
        </div>
        <div class="col-sm-3" class="form-control">
            <button class="btn btn-lg btn-primary">
                <i class="glyphicon glyphicon-save"></i>
                <?=_('Install')?>
            </button>
        </div>
    </div>

    <input type="hidden" name="type" value="beta" />
    <input type="hidden" name="folder" value="<?=$_SERVER['REQUEST_URI']?>" />
 </form>
