<form 
    id="item"
	method="POST" 
	action="<?=__HOME__?>/install/install/"
	>
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend>APP NAME</legend>                    
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label>NOME</label>
            <input type="text" class="form-control" name="nome_app" value="MailCtlr" />
        </div>
    </div>
    
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend>Database</legend>                    
        </div>
    </div>
    
    <div class="form-group">
         <div class="col-sm-12" class="form-control">
             <label>Host</label>
             <input type="text" class="form-control" name="host" value="" placeholder="localhost" />
         </div>
    </div>
    
    <div class="form-group">
         <div class="col-sm-6" class="form-control">
             <label>User</label>
             <input type="text" class="form-control" name="user" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
             <label>Password</label>
             <input type="text" class="form-control" name="pass" value="" />
        </div>
        
    </div>
    
    <div class="form-group">
         <div class="col-sm-6" class="form-control">
             <label>Name</label>
             <input type="text" class="form-control" name="name" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
             <label>Prefix</label>
             <input type="text" class="form-control" name="pref" value="" placeholder="mc_"/>
        </div>
        
    </div>
    
    <div class="form-group">
        <div class="col-sm-12">
            <legend>Dati Utente</legend>                    
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label>Username</label>
            <input type="text" class="form-control" name="u_username" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
            <label>Password</label>
            <input type="text" class="form-control" name="u_password" value="" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-6" class="form-control">
            <label>Nome</label>
            <input type="text" class="form-control" name="nome" value="" />
        </div>
        <div class="col-sm-6" class="form-control">
            <label>Cognome</label>
            <input type="text" class="form-control" name="cognome" value="" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-7" class="form-control">
            <label>Email</label>
            <input type="email" class="form-control" name="email" value="" />
        </div>
        <div class="col-sm-2" class="form-control">
            <label>Newsletter</label>
            <select class="form-control" name="news">
                <option value="1" selected="">SI</option>
                <option value="0">NO</option>
            </select>
        </div>
        <div class="col-sm-3" class="form-control">
            <button class="btn btn-lg btn-primary">
                <i class="glyphicon glyphicon-save"></i>
                INSTALLA
            </button>
        </div>
    </div>

    <input type="hidden" name="type" value="beta" />
    <input type="hidden" name="folder" value="<?=$_SERVER['REQUEST_URI']?>" />
 </form>
