<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/">
    <head>
        <meta charset="utf-8" />
        <title>MailCtlr Installer</title>
        <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="css/style.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
        <script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/i18n/jquery-ui-i18n.min.js?ver=4.1'></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v2.5&appId=1677109185841950";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <div class="container" style="padding-top: 20px;">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">MailCtlr <?=_('Installer')?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-8">
                                <div class="row">
                                    <div class="col-xs-12">											
                                        <?php include(__DIR__.'/form.phtml') ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-4 tmp_choose">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><?=_('Stay Updated')?></h4><br /><br />
                                    <div class="fb-page" data-href="https://www.facebook.com/ctlr.it" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/ctlr.it"><a href="https://www.facebook.com/ctlr.it">ctlr</a></blockquote></div></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <p>
                            &copy; 2015 - <?=date('Y')?> <img src="http://www.ctlr.eu/MailCtlr/store/mailctlr/ctlr.png" alt="ctlr" height="12" style="" /> | <a href="http://www.ctlr.it?ref=newMailCtlr" target="_blank">ctlr.it</a> - <a href="mailto:info@ctlr.it">info@ctlr.it</a></p>
                    </div>
                </div>
        </div>
        <div id="hc"></div>
    </body>
</html>