<form 
	id="item"
	method="POST" 
	action="<?=__HOME__?>/accountSMTP/save/"
	data-ui-validate="success:'<?=$data->modal?'testModalSave':''?>'"
	> 	

	<input type="hidden" name="id" value="<?=$data->item->id?>">
	<input type="hidden" name="created" value="<?=$data->item->created?>">
    
	<ul class="nav nav-tabs">
		<li class="active"><a href="#tab1" data-toggle="tab">Generale</a></li>
	</ul>

	<div class="tab-content border-light">
		<?php include(__DIR__.'/form-tab1.phtml'); ?>
		<div style="clear:both;"></div>
	</div>
				
	<div class="alert alert-info mt20px">(*) Campi obbligatori</div>
	
</form>
