<div class="h70px">
	<nav 
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation"
		>
		<div class="container">
			<div class="navbar-header">    
				<span class="navbar-brand nav-bar-title" ><?=@$data->title ?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
            <div class="navbar-content collapse navbar-collapse">		
				<ul class="nav navbar-nav pull-right">
					<li>
                        <a href="#"><?=_('Current version')?> <b><?=@$data->current?></b></a>
					</li>
				</ul>
			</div>
		</div> 
	</nav>
</div>

<?php foreach ($data->changelog as $changelog) { ?>
    <div class="panel <?php 
    if ($changelog->version_numb == __VERSION__)
        echo 'panel-success';
    else
        echo 'panel-info';
    ?>">
        <div class="panel-heading">
            <h3 class="panel-title"><?=$changelog->title;?></h3>
            <?php 
            if ($changelog->version_numb > __VERSION__)
                echo "<a href='".__HOME__."/changelog/update'>"._('Update')."</a>";
            ?>
        </div>
        <div class="panel-body">
            <?=$changelog->text?>
        </div>
        <ul class="list-group">
            <li class="list-group-item"><span class="badge"><?=$changelog->version_numb;?></span><?=_('Version')?></li>
            <li class="list-group-item"><span class="badge"><?=$changelog->version_type;?></span><?=_('Type')?></li>
            <li class="list-group-item"><span class="badge"><?=$changelog->version_name;?></span><?=_('Name')?></li>
            <li class="list-group-item"><span class="badge"><?=$changelog->data;?></span><?=_('Release date')?></li>
        </ul>
    </div>
<?php } ?>
