<div class="h70px">

	<nav 
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default" 
		role="navigation"
		> 

		<div class="container">

			<div class="navbar-header">    
				<span class="navbar-brand nav-bar-title" ><?=@$data->title ?></span>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toolbar-nav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
            <div class="navbar-content collapse navbar-collapse">		
				<ul class="nav navbar-nav pull-right">
					<li>
                        <a href="#">Versione corrente <b><?=@$data->current?></b></a>
					</li>
				</ul>
			</div>
		</div> 
	</nav>
		
</div>


<?php foreach ($data->changelog as $changelog) { ?>
    <div class="panel <?php 
    if ($changelog->version_numb == __VERSION__)
        echo 'panel-success';
    else
        echo 'panel-info';
    ?>">
        <div class="panel-heading">
            <h3 class="panel-title"><?=$changelog->title;?></h3>
            <?php 
            if ($changelog->version_numb > __VERSION__)
                echo 'UPDATE';
            ?>
        </div>
        <div class="panel-body">
            <?=$changelog->text?>
        </div>

        <ul class="list-group">
            <li class="list-group-item"><span class="badge"><?=$changelog->version_numb;?></span>Versione </li>
            <li class="list-group-item"><span class="badge"><?=$changelog->version_type;?></span>Tipo </li>
            <li class="list-group-item"><span class="badge"><?=$changelog->version_name;?></span>Nome </li>
            <li class="list-group-item"><span class="badge"><?=$changelog->data;?></span> Data di rilascio</li>
        </ul>
    </div>
<?php } ?>
